DAILY_CAPITAL = 5000
BASE_RISK = 0.01

CHECK_INTERVAL = 1800  # 30 mins

NIFTY_50 = [
    "RELIANCE", "TCS", "INFY", "HDFCBANK", "ICICIBANK",
    "LT", "SBIN", "AXISBANK", "ITC"
]

EXCHANGE = "NSE"
PRODUCT = "CNC"