WATCHLIST = [
    # ── Nifty 50 ──────────────────────────────────────────────────────────────
    {"symbol": "RELIANCE.NS",   "name": "Reliance Industries",   "sector": "Energy"},
    {"symbol": "TCS.NS",        "name": "TCS",                   "sector": "IT"},
    {"symbol": "HDFCBANK.NS",   "name": "HDFC Bank",             "sector": "Banking"},
    {"symbol": "INFY.NS",       "name": "Infosys",               "sector": "IT"},
    {"symbol": "ICICIBANK.NS",  "name": "ICICI Bank",            "sector": "Banking"},
    {"symbol": "HINDUNILVR.NS", "name": "HUL",                   "sector": "FMCG"},
    {"symbol": "ITC.NS",        "name": "ITC",                   "sector": "FMCG"},
    {"symbol": "SBIN.NS",       "name": "SBI",                   "sector": "Banking"},
    {"symbol": "BHARTIARTL.NS", "name": "Bharti Airtel",         "sector": "Telecom"},
    {"symbol": "KOTAKBANK.NS",  "name": "Kotak Mahindra Bank",   "sector": "Banking"},
    {"symbol": "WIPRO.NS",      "name": "Wipro",                 "sector": "IT"},
    {"symbol": "HCLTECH.NS",    "name": "HCL Tech",              "sector": "IT"},
    {"symbol": "AXISBANK.NS",   "name": "Axis Bank",             "sector": "Banking"},
    {"symbol": "BAJFINANCE.NS", "name": "Bajaj Finance",         "sector": "Finance"},
    {"symbol": "MARUTI.NS",     "name": "Maruti Suzuki",         "sector": "Auto"},
    {"symbol": "TITAN.NS",      "name": "Titan",                 "sector": "Consumer"},
    {"symbol": "SUNPHARMA.NS",  "name": "Sun Pharma",            "sector": "Pharma"},
    {"symbol": "ONGC.NS",       "name": "ONGC",                  "sector": "Energy"},
    {"symbol": "NTPC.NS",       "name": "NTPC",                  "sector": "Power"},
    {"symbol": "EICHERMOT.NS",  "name": "Eicher Motors",         "sector": "Auto"},
    {"symbol": "DRREDDY.NS",    "name": "Dr Reddy's",            "sector": "Pharma"},
    {"symbol": "NESTLEIND.NS",  "name": "Nestle India",          "sector": "FMCG"},
    {"symbol": "ADANIPORTS.NS", "name": "Adani Ports",           "sector": "Infrastructure"},
    {"symbol": "BAJAJFINSV.NS", "name": "Bajaj Finserv",         "sector": "Finance"},
    {"symbol": "TECHM.NS",      "name": "Tech Mahindra",         "sector": "IT"},
    {"symbol": "HINDALCO.NS",   "name": "Hindalco",              "sector": "Metals"},
    {"symbol": "COALINDIA.NS",  "name": "Coal India",            "sector": "Energy"},
    {"symbol": "JSWSTEEL.NS",   "name": "JSW Steel",             "sector": "Metals"},
    {"symbol": "BAJAJ-AUTO.NS", "name": "Bajaj Auto",            "sector": "Auto"},
    {"symbol": "POWERGRID.NS",  "name": "Power Grid",            "sector": "Power"},
    {"symbol": "LT.NS",         "name": "Larsen & Toubro",       "sector": "Infrastructure"},
    {"symbol": "M&M.NS",        "name": "Mahindra & Mahindra",   "sector": "Auto"},
    {"symbol": "ULTRACEMCO.NS", "name": "UltraTech Cement",      "sector": "Cement"},
    {"symbol": "ASIANPAINT.NS", "name": "Asian Paints",          "sector": "Consumer"},
    {"symbol": "TMPV.NS", "name": "Tata Motors",           "sector": "Auto"},
    {"symbol": "INDUSINDBK.NS", "name": "IndusInd Bank",         "sector": "Banking"},
    {"symbol": "TATACONSUM.NS", "name": "Tata Consumer",         "sector": "FMCG"},
    {"symbol": "BPCL.NS",       "name": "BPCL",                  "sector": "Energy"},
    {"symbol": "CIPLA.NS",      "name": "Cipla",                 "sector": "Pharma"},
    {"symbol": "GRASIM.NS",     "name": "Grasim Industries",     "sector": "Cement"},
    {"symbol": "ADANIENT.NS",   "name": "Adani Enterprises",     "sector": "Infrastructure"},
    {"symbol": "TATASTEEL.NS",  "name": "Tata Steel",            "sector": "Metals"},
    {"symbol": "TRENT.NS",      "name": "Trent",                 "sector": "Consumer"},
    {"symbol": "BRITANNIA.NS",  "name": "Britannia Industries",  "sector": "FMCG"},
    {"symbol": "APOLLOHOSP.NS", "name": "Apollo Hospitals",      "sector": "Healthcare"},
    {"symbol": "BEL.NS",        "name": "Bharat Electronics",    "sector": "Defense"},
    {"symbol": "HEROMOTOCO.NS", "name": "Hero MotoCorp",         "sector": "Auto"},
    {"symbol": "SBILIFE.NS",    "name": "SBI Life Insurance",    "sector": "Insurance"},
    {"symbol": "HDFCLIFE.NS",   "name": "HDFC Life Insurance",   "sector": "Insurance"},
    {"symbol": "SHRIRAMFIN.NS", "name": "Shriram Finance",       "sector": "Finance"},
    # ── Nifty Next 50 ─────────────────────────────────────────────────────────
    {"symbol": "HAVELLS.NS",    "name": "Havells India",         "sector": "Consumer"},
    {"symbol": "SIEMENS.NS",    "name": "Siemens India",         "sector": "Industrial"},
    {"symbol": "DLF.NS",        "name": "DLF",                   "sector": "Realty"},
    {"symbol": "ETERNAL.NS",     "name": "Zomato",                "sector": "Consumer"},
    {"symbol": "PIDILITIND.NS", "name": "Pidilite Industries",   "sector": "Chemicals"},
    {"symbol": "MARICO.NS",     "name": "Marico",                "sector": "FMCG"},
    {"symbol": "COLPAL.NS",     "name": "Colgate-Palmolive",     "sector": "FMCG"},
    {"symbol": "DABUR.NS",      "name": "Dabur India",           "sector": "FMCG"},
    {"symbol": "GODREJCP.NS",   "name": "Godrej Consumer",       "sector": "FMCG"},
    {"symbol": "TORNTPHARM.NS", "name": "Torrent Pharma",        "sector": "Pharma"},
    {"symbol": "LUPIN.NS",      "name": "Lupin",                 "sector": "Pharma"},
    {"symbol": "ZYDUSLIFE.NS",  "name": "Zydus Lifesciences",    "sector": "Pharma"},
    {"symbol": "ALKEM.NS",      "name": "Alkem Laboratories",    "sector": "Pharma"},
    {"symbol": "PERSISTENT.NS", "name": "Persistent Systems",    "sector": "IT"},
    {"symbol": "MPHASIS.NS",    "name": "Mphasis",               "sector": "IT"},
    {"symbol": "COFORGE.NS",    "name": "Coforge",               "sector": "IT"},
    {"symbol": "LTTS.NS",       "name": "L&T Technology",        "sector": "IT"},
    {"symbol": "NAUKRI.NS",     "name": "Info Edge (Naukri)",    "sector": "IT"},
    {"symbol": "HAL.NS",        "name": "HAL",                   "sector": "Defense"},
    {"symbol": "IRCTC.NS",      "name": "IRCTC",                 "sector": "Consumer"},
    {"symbol": "CHOLAFIN.NS",   "name": "Cholamandalam Finance", "sector": "Finance"},
    {"symbol": "MUTHOOTFIN.NS", "name": "Muthoot Finance",       "sector": "Finance"},
    {"symbol": "DMART.NS",      "name": "Avenue Supermarts",     "sector": "Consumer"},
    {"symbol": "PAGEIND.NS",    "name": "Page Industries",       "sector": "Consumer"},
    {"symbol": "OBEROIRLTY.NS", "name": "Oberoi Realty",         "sector": "Realty"},
    # ── Small / Mid Cap additions ──────────────────────────────────────────────
    {"symbol": "FEDERALBNK.NS", "name": "Federal Bank",           "sector": "Banking"},
    {"symbol": "IDFCFIRSTB.NS", "name": "IDFC First Bank",        "sector": "Banking"},
    {"symbol": "CANBK.NS",      "name": "Canara Bank",            "sector": "Banking"},
    {"symbol": "BANKBARODA.NS", "name": "Bank of Baroda",         "sector": "Banking"},
    {"symbol": "TATAELXSI.NS",  "name": "Tata Elxsi",            "sector": "IT"},
    {"symbol": "KPITTECH.NS",   "name": "KPIT Technologies",      "sector": "IT"},
    {"symbol": "POLYCAB.NS",    "name": "Polycab India",          "sector": "Consumer"},
    {"symbol": "DIXON.NS",      "name": "Dixon Technologies",     "sector": "Consumer"},
    {"symbol": "BERGEPAINT.NS", "name": "Berger Paints",          "sector": "Consumer"},
    {"symbol": "VOLTAS.NS",     "name": "Voltas",                 "sector": "Consumer"},
    {"symbol": "JUBLFOOD.NS",   "name": "Jubilant FoodWorks",     "sector": "Consumer"},
    {"symbol": "BATAINDIA.NS",  "name": "Bata India",             "sector": "Consumer"},
    {"symbol": "INDIGO.NS",     "name": "IndiGo",                 "sector": "Consumer"},
    {"symbol": "ANGELONE.NS",   "name": "Angel One",              "sector": "Finance"},
    {"symbol": "SBICARD.NS",    "name": "SBI Cards",              "sector": "Finance"},
    {"symbol": "ICICIGI.NS",    "name": "ICICI Lombard",          "sector": "Insurance"},
    {"symbol": "LALPATHLAB.NS", "name": "Dr Lal PathLabs",        "sector": "Healthcare"},
    {"symbol": "METROPOLIS.NS", "name": "Metropolis Healthcare",  "sector": "Healthcare"},
    {"symbol": "ASTRAL.NS",     "name": "Astral Ltd",             "sector": "Chemicals"},
    {"symbol": "AARTIIND.NS",   "name": "Aarti Industries",       "sector": "Chemicals"},
    {"symbol": "BOSCHLTD.NS",   "name": "Bosch India",            "sector": "Industrial"},
    {"symbol": "ESCORTS.NS",    "name": "Escorts Kubota",         "sector": "Auto"},
    {"symbol": "MOTHERSON.NS",  "name": "Samvardhana Motherson",  "sector": "Auto"},
    {"symbol": "CUMMINSIND.NS", "name": "Cummins India",          "sector": "Industrial"},
    {"symbol": "LODHA.NS",      "name": "Macrotech Developers",   "sector": "Realty"},
]

SECTOR_SYMBOLS = {
    "Banking":        "^NSEBANK",
    "IT":             "^CNXIT",
    "Pharma":         "^CNXPHARMA",
    "Auto":           "^CNXAUTO",
    "FMCG":           "^CNXFMCG",
    "Energy":         "^CNXENERGY",
    "Metals":         "^CNXMETAL",
    "Realty":         "^CNXREALTY",
}

RISK_SECTORS = {
    "Conservative": ["Banking", "FMCG", "Pharma", "Power", "Healthcare", "Insurance"],
    "Moderate":     ["Banking", "IT", "FMCG", "Auto", "Pharma", "Finance", "Healthcare", "Cement", "Defense", "Chemicals"],
    "Aggressive":   ["IT", "Auto", "Metals", "Finance", "Telecom", "Infrastructure", "Consumer", "Realty", "Industrial"],
}